version: 2
registries:
  pypi:
    type: python-index
    url: https://pypi.org/simple
    username: ""
    password: ""
  pytorch:
    type: python-index
    url: https://download.pytorch.org/whl/cu130
    username: ""
    password: ""
updates:
  # Enable version updates for Python dependencies
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "vasudev-gm"
    assignees:
      - "vasudev-gm"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
    registries:
      - pypi
      - pytorch

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "vasudev-gm"
    assignees:
      - "vasudev-gm"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
